version: "3.9"

services:
  app:
    image: appimage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - .:/app
    container_name: appcontainer
